version: '3.8'
services:
  myapp:
    deploy:
      resources:
        limits:
          cpus: '0,5'
          memory: 512M
        reservations:
          cpus: '0,5'
          memory: 256M
    image: myapp:latest
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        progress: plain
    entrypoint: ["sh", "/certs/entrypoint.sh"]
    ports:
      - 5000:5000
    volumes:
      - ./app.py:/app/app.py
      - ${key_folder:-./xxx.000}:/var/opt/cprocsp/keys/root/xxx.000
      - ./certs:/certs
    environment:
      - production: true
